.TH "sirvecole" "8" "" "" ""
.SH "NAME"
sirvecole \(em controlaula daemon 
.SH "SYNOPSIS"
.B sirvecole
.SH "DESCRIPTION"
The \fIsirvecole\fP daemon runs listening  for orders from the teacher. When an identified teacher order is parsed, it executes it.
For this to work, a real teacher in a pc identified as a teacher pc must be running ControlAula.

.SH "OPTIONS"
.PP 
This program accepts no options
.SH "SEE ALSO"
The official ControlAula documentation:
.RS
.B http://www.itais.net/help/en/
.SH "AUTHOR"
.PP 
sirvecole was written by José L. Redrejo Rodríguez
 
.PP 
This manual page was written by José L. Redrejo Rodríguez 
<jredrejo at debian.org> for the Debian system (but may 
be used by others).  Permission is granted to copy, distribute 
and/or modify this document under the terms of the GNU 
Free Documentation License, Version 1.1 or any later 
version published by the Free Software Foundation; with no 
Invariant Sections, no Front\-Cover Texts and no Back\-Cover 
Texts. 

